# Generated by Django 2.2.6 on 2019-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.TextField()),
                ('name', models.TextField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'whiskey',
                'ordering': ['name'],
            },
        ),
    ]
